export const TYPE_SET = 'TYPE_SET';
export const SCRAMBLE_GENERATED = 'SCRAMBLE_GENERATED';
export const STATE_SET = 'STATE_SET';
export const HOLDING_STARTED = 'HOLDING_STARTED';
export const HOLDING_STOPPED = 'HOLDING_STOPPED';
export const TIMER_STARTED = 'TIMER_STARTED';
export const TIMER_STOPPED = 'TIMER_STOPPED';
