// timer
export const TYPE_SET = 'TYPE_SET';
export const SCRAMBLE_GENERATED = 'SCRAMBLE_GENERATED';
export const STATE_SET = 'STATE_SET';
export const INSPECTION_STARTED = 'INSPECTION_STARTED';
export const HOLDING_STARTED = 'HOLDING_STARTED';
export const HOLDING_STOPPED = 'HOLDING_STOPPED';
export const TIMER_STARTED = 'TIMER_STARTED';
export const TIMER_STOPPED = 'TIMER_STOPPED';
export const SPACEBAR_IS_DOWN_SET = 'SPACEBAR_IS_DOWN_SET';

// settings
export const INSPECTION_SET = 'INSPECTION_SET';
export const HOLD_TIME_SET = 'HOLD_TIME_SET';
export const DISPLAY_MILLIS_SET = 'DISPLAY_MILLIS_SET';
export const HIDE_SOLVE_TIME_SET = 'HIDE_SOLVE_TIME_SET';

// modal
export const MODAL_CREATED = 'MODAL_CREATED';
export const MODAL_REMOVED = 'MODAL_REMOVED';
export const MODAL_STATE_SET = 'MODAL_STATE_SET';