const colorSchemes = [
  {
    name: 'Custom',
    value: 'CUSTOM',
  },
  {
    name: 'Default',
    value: 'DEFAULT',
    cssClassName: 'color-scheme-default',
    colors: {
      sideBarTop: '#555FFF',
      sideBarBottom: '#555FFF',
      sideBarText: '#FFFFFF',
      topBarLeft: '#1E90FF',
      topBarRight: '#1E90FF',
      topBarText: '#FFFFFF',
      buttons: '#00DDDD',
      buttonsText: '#FFFFFF',
      background: '#FFFFFF',
      backgroundText: '#000000',
      glow: '#228DFF',
    },
  },
  {
    name: 'Forest',
    value: 'FOREST',
    cssClassName: 'color-scheme-forest',
    colors: {
      sideBarTop: '#083D06',
      sideBarBottom: '#083D06',
      sideBarText: '#FFFFFF',
      topBarLeft: '#0D6102',
      topBarRight: '#0D6102',
      topBarText: '#FFFFFF',
      buttons: '#397E39',
      buttonsText: '#FFFFFF',
      background: '#C5FFC2',
      backgroundText: '#000000',
      glow: '#397E39',
    },
  },
  {
    name: 'Hacker (Green)',
    value: 'HACKER_GREEN',
    cssClassName: 'color-scheme-hacker-green',
    colors: {
      sideBarTop: '#000000',
      sideBarBottom: '#000000',
      sideBarText: '#00FF00',
      topBarLeft: '#000000',
      topBarRight: '#000000',
      topBarText: '#00FF00',
      buttons: '#000000',
      buttonsText: '#00FF00',
      background: '#000000',
      backgroundText: '#00FF00',
      glow: '#000000',
    },
  },
  {
    name: 'Hacker (Pink)',
    value: 'HACKER_PINK',
    cssClassName: 'color-scheme-hacker-pink',
    colors: {
      sideBarTop: '#000000',
      sideBarBottom: '#000000',
      sideBarText: '#FF00FF',
      topBarLeft: '#000000',
      topBarRight: '#000000',
      topBarText: '#FF00FF',
      buttons: '#000000',
      buttonsText: '#FF00FF',
      background: '#000000',
      backgroundText: '#FF00FF',
      glow: '#000000',
    },
  },
  {
    name: 'Plum',
    value: 'PLUM',
    cssClassName: 'color-scheme-plum',
    colors: {
      sideBarTop: '#341236',
      sideBarBottom: '#341236',
      sideBarText: '#F7D0FF',
      topBarLeft: '#612263',
      topBarRight: '#612263',
      topBarText: '#D48CD8',
      buttons: '#3F143E',
      buttonsText: '#FDE6FF',
      background: '#EBD1F3',
      backgroundText: '#000000',
      glow: '#3F143E',
    },
  },
  {
    name: 'Ocean',
    value: 'OCEAN',
    cssClassName: 'color-scheme-ocean',
    colors: {
      sideBarTopp: '#5E73BC',
      sideBarBottom: '#5E73BC',
      sideBarText: '#E7E1EC',
      topBarLeft: '#002263',
      topBarRight: '#002263',
      topBarText: '#DBE5FF',
      buttons: '#3D4A77',
      buttonsText: '#D1D6F2',
      background: '#353E73',
      backgroundText: '#FFFFFF',
      glow: '#3D4A77',
    },
  },
  {
    name: 'Sunset',
    value: 'SUNSET',
    cssClassName: 'color-scheme-sunset',
    colors: {
      sideBarTop: '#FF5580',
      sideBarBottom: '#005580',
      sideBarText: '#E7E1EC',
      topBarLeft: '#FF5580',
      topBarRight: '#FFFF80',
      topBarText: '#DBE5FF',
      buttons: '#FFFFFF',
      buttonsText: '#005580',
      background: '#FFFFFF',
      backgroundText: '#000000',
      glow: '#3D4A77',
    },
  },
  {
    name: 'Desert',
    value: 'DESERT',
    cssClassName: 'color-scheme-desert',
    colors: {
      sideBarTop: '#8A5115',
      sideBarBottom: '#8A5115',
      sideBarText: '#E7E1EC',
      topBarLeft: '#D79840',
      topBarRight: '#D79840',
      topBarText: '#F3DD87',
      buttons: '#C97D1A',
      buttonsText: '#F2EFAE',
      background: '#F3DD87',
      backgroundText: '#5D3400',
      glow: '#C97D1A',
    },
  },
  {
    name: 'Aurora',
    value: 'AURORA',
    cssClassName: 'color-scheme-aurora',
    colors: {
      sideBarTop: '#002286',
      sideBarBottom: '#573464',
      sideBarText: '#E7E1EC',
      topBarLeft: '#002286',
      topBarRight: '#573464',
      topBarText: '#DBE5FF',
      buttons: '#FFFFFF', // don't remember
      buttonsText: '#000000', // don't remember
      background: '#E7E1EC',
      backgroundText: '#000000', // I think this was black
      glow: '#FFFFFF',
    },
  },
];

export default colorSchemes;